### ISSUE TITLE
好像这张图放错了

### ISSUE THREAD

**Issue by SekiBetu** [jerryc127/butterfly.js.org#13]
https://butterfly.js.org/posts/4aa8abbe/#%E5%9C%96%E7%89%87%E6%8F%8F%E8%BF%B0
https://github.com/jerryc127/butterfly.js.org/blob/main/source/_posts/Butterfly-%E5%AE%89%E8%A3%9D%E6%96%87%E6%AA%94-%E4%B8%89-%E4%B8%BB%E9%A1%8C%E9%85%8D%E7%BD%AE-1.md
![image](https://user-images.githubusercontent.com/38283893/109044076-f2197680-770c-11eb-9925-95dcc3c417c6.png)

**Comment by jerryc127** [comment]
没错啊

**Comment by SekiBetu** [comment]
是我搞错了，原来这是博客的截图，我以为是什么
